markdown: rdiscount
pygments: true
paginate: 3

permalink: "/:year/:month/:day/:title"

title: "A Trivial Hero"
baseurl: http://atrivialhero.com

description: "Official website for A Trivial Hero, a band based in Las Vegas that performs both acoustic and full-band eclectic rock."
keywords: "A Trivial Hero, A.J. Crame, Phillip Black, Las Vegas music, eclectic rock, nerd rock, acoustic rock, punk, alternative"
contact: officiallytrivial@gmail.com

facebook: "https://www.facebook.com/pages/A-Trivial-Hero/15779138323"
instagram: "http://instagram.com/aj_atrivialhero"
youtube: "http://www.youtube.com/user/atrivialhero"

s3-images: https://s3-us-west-2.amazonaws.com/atrivialhero.com/images